"""fix schema and model mismatch error

Revision ID: 56960129df55
Revises: c01769abb920
Create Date: 2025-05-21 22:09:12.196772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# TODO: add new this
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '56960129df55'
down_revision: Union[str, None] = 'c01769abb920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_txt', sa.VARCHAR(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('book_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user_accounts.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_constraint('user_accounts_uid_key', 'user_accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_accounts_uid_key', 'user_accounts', ['uid'])
    op.drop_table('reviews')
    # ### end Alembic commands ###
